#!/bin/bash


PRODUCTION_ENV=$1
WORKSPACE=$(pwd)
PORT=5001

# Check if .venv exists
if [ ! -d "${WORKSPACE}/.venv/" ]; then
    echo "Creating virtual environment ${WORKSPACE}/.venv"
    # Create virtual environment
    python3 -m venv "$WORKSPACE/.venv"
fi

# Source virtual environment
echo "Sourcing venv"
source "$WORKSPACE/.venv/bin/activate"
# Install requirements
echo "Installing requirements"
pip install -r "$WORKSPACE/requirements.txt"


# Check if using test environment
echo "Checking server type server"
if [ "$PRODUCTION_ENV" = "production" ]; then
  echo "USING PRODUCTION PORT"
  PORT=5000
fi

# Point to the main flask application
echo "Setting flask app"
export FLASK_APP=$WORKSPACE/webpage_builder.py

# Start the flask server
echo "Starting flask app"
flask run --host=0.0.0.0 -p "$PORT"
#flask run --host=0.0.0.0 -p "$PORT" --cert=adhoc


