#!/bin/bash

PORT=5001
PRODUCTION_ENV=$1
WORKSPACE=$(pwd)
PYTHON_VENV="${WORKSPACE}/.venv"

# Check if .venv exists
if [ ! -d "${PYTHON_VENV}" ]; then
    echo "Missing: ${PYTHON_VENV}"
    exit 1
fi

# Source virtual environment
echo "Sourcing venv"
source "${PYTHON_VENV}/bin/activate"

# Check if using test environment
echo "Checking server type server"
if [ "${PRODUCTION_ENV}" = "production" ]; then
    echo "USING PRODUCTION PORT"
    PORT=5000
fi

# Point to the main flask application
echo "Setting flask app"
export FLASK_APP="${WORKSPACE}/flask_endpoints.py"

# Start the flask server
echo "Starting flask app"
flask run --host=0.0.0.0 -p "${PORT}"

